#!/bin/bash

source /opt/toolchain/utils/toolchain-utils-load
if [[ $TT ]] ;then
    tt $TT $TT_CCACHE
fi

cd /mntdir/$WD

export SSH_AUTH_SOCK=/var/tmp/agentBridge.sock
socat UNIX-LISTEN:$SSH_AUTH_SOCK,reuseaddr,fork TCP:docker.for.mac.localhost:$SSH_AUTH_PORT &
exec "$@"
